### ISSUE TITLE
NoMethodError (undefined method `[]' for nil:NilClass):

### ISSUE THREAD

**Issue by JReverse** [akif2543/disarray#13]
NoMethodError (undefined method `[]' for nil:NilClass):

(erb):19:in `<main>'
app/models/user.rb:143:in `ensure_avatar'
app/controllers/api/users_controller.rb:18:in `create'

Also

get NoMethodError (undefined method `[]' for nil:NilClass) at bundle exec rails db:seed

**Comment by werewolf26** [comment]
yea get the same error too

**Comment by werewolf26** [comment]
yea keep get a same error code too 
![image_2021-03-27_054119](https://user-images.githubusercontent.com/45981158/112716830-0e9d0000-8ebf-11eb-80c4-3a89e6472b56.png) look like in app/controllers/api/users_controller.rb:18

**Comment by akif2543** [comment]
hey there, @JReverse and @werewolf26! 

Sorry, for the very late response. Could you give me a bit more context so I can try to reproduce these errors? What did you do in order to produce them? Did you change any of the code compared to what's there on the master branch?

If it just has to do with seeding, I noticed that I forgot to mention in the `README` that the Rails server needs to be running during seeding in order for the default avatar images to be available. I updated that and I also added a `begin/rescue` block to the `User` model's `ensure_avatar` method in the meantime to skip it if an error occurs while trying to open a default avatar.

**Comment by werewolf26** [comment]
> hey there, @JReverse and @werewolf26! 
> 
> Sorry, for the very late response. Could you give me a bit more context so I can try to reproduce these errors? What did you do in order to produce them? Did you change any of the code compared to what's there on the master branch?
> 
> If it just has to do with seeding, I noticed that I forgot to mention in the `README` that the Rails server needs to be running during seeding in order for the default avatar images to be available. I updated that and I also added a `begin/rescue` block to the `User` model's `ensure_avatar` method in the meantime to skip it if an error occurs while trying to open a default avatar. 
> 
Will I did everything in the readme but so get the same error so yea

**Comment by akif2543** [comment]
Aha, I found the culprit. The `credentials.yml.enc` file requires my master key, so I created a new branch called `clone` without that file or any other references to my personal config. I cloned it to a new repo and tried to install everything myself and it worked. Go ahead and pull the `clone` branch into your local master and give it a go. I also updated the `README` to reflect this. Let me know if it works.

**Comment by werewolf26** [comment]
> Aha, I found the culprit. The `credentials.yml.enc` file requires my master key, so I created a new branch called `clone` without that file or any other references to my personal config. I cloned it to a new repo and tried to install everything myself and it worked. Go ahead and pull the `clone` branch into your local master and give it a go. I also updated the `README` to reflect this. Let me know if it works.

yap it working thank you for fix the issues.
